#### Example data ####

#' examplePeaks
#'
#' @return list of GRanges of peak calls
#' @export
#'
#' @examples
#' examplePeaks()
examplePeaks = function(){
    CTCF_in_10a_narrowPeak_grs = NULL
    utils::data("CTCF_in_10a_narrowPeak_grs", package = "seqsetvis", overwrite = TRUE, envir = environment())
    peaks_gr = CTCF_in_10a_narrowPeak_grs
    peaks_gr
}

#' exampleQueryGR
#'
#' @return GRanges example
#' @export
#'
#' @importFrom GenomicRanges mcols
#' @examples
#' exampleQueryGR()
exampleQueryGR = function(){
    CTCF_in_10a_overlaps_gr = NULL
    utils::data("CTCF_in_10a_overlaps_gr", package = "seqsetvis", overwrite = TRUE, envir = environment())
    query_gr = CTCF_in_10a_overlaps_gr
    colnames(GenomicRanges::mcols(query_gr)) = paste0(
        "peak_",
        colnames(GenomicRanges::mcols(query_gr))
    )
    query_gr
}

#' exampleProfDT
#'
#' @return data.table example
#' @export
#' @importFrom utils data
#'
#' @examples
#' exampleProfDT()
exampleProfDT = function(){
    CTCF_in_10a_profiles_dt = NULL
    utils::data(list = "CTCF_in_10a_profiles_dt", package = "seqsetvis", overwrite = TRUE, envir = environment())
    CTCF_in_10a_profiles_dt = translateSSVtoCT2(CTCF_in_10a_profiles_dt)
    CTCF_in_10a_profiles_dt[]
}

#' query_gr
#'
#' @return ChIPtsne object for testing
#' @export
#'
#' @examples
#' exampleChIPtsne2()
exampleChIPtsne2 = function(){
    query_gr = exampleQueryGR()
    prof_dt = exampleProfDT() %>%
        translateSSVtoCT2

    ChIPtsne2.from_tidy(prof_dt, query_gr)
}

#' exampleChIPtsne2.with_meta
#'
#' @return ChIPtsne object for testing, includes meta data
#' @export
#' @importFrom tidyr separate
#'
#' @examples
#' exampleChIPtsne2.with_meta()
exampleChIPtsne2.with_meta = function(){
    query_gr = exampleQueryGR()
    prof_dt = exampleProfDT()
    meta_dt = prof_dt %>%
        translateSSVtoCT2 %>%
        dplyr::select(name) %>%
        unique %>%
        tidyr::separate(name, c("cell", "mark"), sep = "_", remove = FALSE)

    ChIPtsne2.from_tidy(prof_dt, query_gr, sample_metadata = meta_dt)
}

#' exampleBamFiles
#'
#' @return character file paths to example bam files.
#' @export
#'
#' @examples
#' exampleBamFiles()
exampleBamFiles = function(){
    dir(system.file("extdata", package = "chiptsne2"), pattern = "MCF.+bam$", full.names = TRUE)
}

#' exampleBigWigFiles
#'
#' @return character file paths to example bigWig files.
#' @export
#'
#' @examples
#' exampleBigWigFiles()
exampleBigWigFiles = function(){
    dir(system.file("extdata", package = "seqsetvis"), pattern = "bw$", full.names = TRUE)
}

#' exampleBamConfigFile
#'
#' @return character file path to example bam config file.
#' @export
#'
#' @examples
#' exampleBamConfigFile()
exampleBamConfigFile = function(){
    system.file("extdata/bam_config.csv", package = "chiptsne2", mustWork = TRUE)
}

#' exampleBigWigConfigFile
#'
#' @return character file path to example bigWig config file.
#' @export
#'
#' @examples
#' exampleBigWigConfigFile()
exampleBigWigConfigFile = function(){
    system.file("extdata/bigwig_config.csv", package = "chiptsne2", mustWork = TRUE)
}

#' exampleBam_data.frame
#'
#' @return data.frame with example bam files and metadata.
#' @export
#'
#' @examples
#' exampleBam_data.frame()
exampleBam_data.frame = function(){
    bam_config_file = exampleBamConfigFile()
    bam_config_df = .parse_config_body(bam_config_file)
    pkg_dir = system.file(package = "chiptsne2", "extdata", mustWork = TRUE)
    bam_config_df$file = file.path(pkg_dir, bam_config_df$file)
    bam_config_df


}

#' exampleBigWig_data.frame
#'
#' @return data.frame with example bigWig files and metadata.
#' @export
#'
#' @examples
#' exampleBigWig_data.frame()
exampleBigWig_data.frame = function(){
    bigwig_config_file = exampleBigWigConfigFile()
    bigwig_config_df = .parse_config_body(bigwig_config_file)
    pkg_dir = system.file(package = "chiptsne2", "extdata", mustWork = TRUE)
    bigwig_config_df$file = file.path(pkg_dir, bigwig_config_df$file)
    bigwig_config_df
}

#' exampleDataPaths
#'
#' @return data.frame with URL paths to FE bigwigs and narrowPeak files.
#' @export
#'
#' @examples
#' exampleDataPaths()
exampleDataPaths = function(){
    url_dt = data.table::fread(system.file("extdata/example_data_paths.csv", package = "chiptsne2", mustWork = TRUE))
    url_dt[, bw_file := paste0(cell, "_", mark, "_FE.bw")]
    url_dt[, narrowPeak_file := paste0(cell, "_", mark, ".narrowPeak")]
    url_dt[]
}

#' translateSSVtoCT2
#'
#' *seqsetvis* creates data.table with certain default variables that *chiptsne2* uses more user-friendly values for. This function checks for *seqsetvis* defaults and converts them to *chiptsne2*.
#'
#' @param prof_dt A data.table generated by *seqsetvis* from ssvFetchGRanges
#'
#' @return The input `prof_dt` with colnames updated to be compatible with *chiptsne2*.
#' @export
#'
#' @examples
#' prof_dt = exampleProfDT()
#' prof_dt = translateSSVtoCT2(prof_dt)
#' ct2 = ChIPtsne2.from_tidy(prof_dt, exampleQueryGR())
translateSSVtoCT2 = function(prof_dt){
    #convert to data.table if needed
    if(!is(prof_dt, "data.table")){
        prof_dt = data.table::as.data.table(prof_dt)
    }
    if("id" %in% colnames(prof_dt)){
        data.table::setnames(prof_dt, "id", "region")
    }
    if("x" %in% colnames(prof_dt)){
        data.table::setnames(prof_dt, "x", "position")
    }
    if("sample" %in% colnames(prof_dt)){
        data.table::setnames(prof_dt, "sample", "name")
    }
    if("y" %in% colnames(prof_dt)){
        data.table::setnames(prof_dt, "y", "signal")
    }
    prof_dt[]
}
